### ISSUE TITLE
Appears to be working but I hear nothing

### ISSUE THREAD

**Issue by NevadaEchoDelta** [ken107/read-aloud#10]
It's installed, it shows that it's working, but I hear nothing. I have the volume up and nothing else open that plays any sound. I have verified that my soundcard IS working properly. Please help and thank you in advance!

**Comment by ken107** [comment]
Could you go to this page and see if Speech Synthesis work?
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/speechsynthesis/

**Comment by NevadaEchoDelta** [comment]
There was no sound. It had the active speaker icon going whilst it was playing, but no sound.

**Comment by ken107** [comment]
Are you able to watch YouTube videos and hear sound normally?  Obviously the problem is not with the Read Aloud extension, since you couldn't hear sound using the website above, but probably an issue with either the browser or with your OS' audio settings.  Please try some of these troubleshooting sites:

http://www.tomshardware.com/forum/58092-63-sound-browser-only
https://productforums.google.com/forum/#!topic/chrome/RR7hyy0V7Io

**Comment by NevadaEchoDelta** [comment]
Yes, YouTube I can hear normally. I was able to finally get it fixed by disabling all speaker enhancements. Thank you for your help with this and I am eager to start using it!
