### ISSUE TITLE
[Question] Is "Access your data to translate.google.com" always used ?

### ISSUE THREAD

**Issue by Nokia808** [ken107/read-aloud#160]
Hi dear.
I would like to ask: your add-on need this permission "access your data to translate.google.com"
Does this permission used always or only if user select a google voice ? When it utilized exactly ?
Does it be used if user select "automatic selection" or locally installed voice ? 

It will be very bad if this add-on always using this permission whatever voice selection .....

**Comment by ken107** [comment]
Hi,

It's really not that bad, security-wise.  Because translate.google.com is a simple webpage that doesn't require login or collect user data, or do much otherwise.

The rationale for having this permission by default is, we expect GoogleTranslate voices to be the auto-selected voice when the browser does not have any locally-installed voice matching the user's default language (which is usually the case for international languages).  In those cases, it's nice if the GoogleTranslate voice would just work, rather than having to ask the user for permission first.

But let's think more about it.  Thank you for the suggestion.

**Comment by Nokia808** [comment]
@ken107 
Thank you for response.
Dear I'm on Fedora Linux & already installed on my system by default espeak-ng engine & when I set your add-on on "Autoselect" it selected the voices available by espeak-en. So, does this mean in my case that no data reach to translate.google.com or your add-on make a connection with translate.google.com ?

**Comment by ken107** [comment]
It does not make connection with translate.google.com unless you select a "GoogleTranslate XX" voice.  No worries, it only does the minimum it needs to get the job done.

**Comment by Nokia808** [comment]
@ken107 
Okay, it is now clear: no connection with translate.google.com UNLESS add-on not found something else other than Google (or if it is already set to use a Google voice) ....

I will close this issue. But, please be sure that Google not benign from point of privacy at all (including all it's services without any exception). Google model of work is based on "NO privacy"
