### ISSUE TITLE
[Feature request] Make this extension works off-line if find (or set) to use local voice

### ISSUE THREAD

**Issue by Nokia808** [ken107/read-aloud#161]
Hi dear developer.
Currently, this nice add-on not working off-line even if finds local voice or set to use local voice !

To reproduce the issue: 
- open browser on a page with text contents,
- download this page as (HTML, complete),
- set add-on to utilize locally available voice on your PC,
- close browser,
- switch off WiFi (or other source of Internet),
- use browser to open downloaded page & try to use add-on to read aloud. It will failed.

This is a shortage & it will be very useful if make it working off-line as long as it finds or set to use local voice already existing on PC.

**Comment by ken107** [comment]
Hi,

If you selected one of the "Google XX" voices, such as "Google US English", they will have this issue because they're actually not local.  I think Chrome is calling some cloud service to synthesize these voices behind the scene.

If you're on Windows, picking "Microsoft David Desktop" and others will work offline.  Or if you install [this extension](https://chrome.google.com/webstore/detail/us-english-female-text-to/pkidpnnapnfgjhfhkpmjpbckkbaodldb), it will add a voice named "US English Female TTS (by Google)", this will also work offline.  Or if you have purchased IVONA or Nuance voices and installed them on your Windows computer, they will work offline as well.
