### ISSUE TITLE
read-aloud stopped working

### ISSUE THREAD

**Issue by JoeCodeswell** [ken107/read-aloud#2]
Hi Ken,

For Chrome, windows 10, reading content of "http://flask.pocoo.org/docs/0.11/blueprints/",
Paragraph content "So if you have a blueprint in the folder yourapplication/admin and you want to render the template 'admin/index.html' and you have provided templates as a template_folder you will have to create a file like this: yourapplication/admin/templates/admin/index.html.",

read-aloud stopped reading and will NOT read any other paragraph, even after page refresh.

Thanks for the help.

Love and peace,
Joe

**Comment by JoeCodeswell** [comment]
Dear Hai,
I just restarted Chrome and read-aloud began to work again on the SAME PAGE but in a DIFFRENT PARAGRAPH. When i selected the Paragraph content "So if you have a blueprint ..." again and asked read-aloud to read it, read-aloud crashed when reading "file like this: yourapplication/admin/templates/admin/index.html", i think just before "/admin/index.html". This is the SAME PLACE it crashed in the first instance.

Thanks for the help.

Love and peace,
Joe

**Comment by ken107** [comment]
Thank you Joe!  This is an issue with Chrome TTS engine tracked here: 
https://bugs.chromium.org/p/chromium/issues/detail?id=335907

As I commented towards the end, the TTS hangs if the sentence is too long, i.e. around 43 words.  More precisely 43 syllables.  I worked around it by breaking up long sentences.  In your case, the URL path is treated as one word, and so the broken up sentence is still >43 syllables causing TTS to hang.

Actually Read-Aloud will remove all URLs from the text before reading.  In this case though the URLs don't have the http://, so they weren't removed.  Ideally, I need to count syllables rather than words.  Let me think if I can put in a good fix for this.

**Comment by JoeCodeswell** [comment]
Dear Hai,

Thanks for the detailed answer. I will FOR SURE remain a  Read-Aloud user.
I wonder if you could look for w in words where, len(w) > x. then see if you find something like the pattern "[\w*/]*".

ANYWAY, I'm sure you'll find a good fix.

Thanks again, Hai.
Love and peace,
Joe

**Comment by ken107** [comment]
I finally grab what you're talking about :+1:.  I have implemented:
`if word.length >= 14 then word.split("/_@")`

This will split up long words, paths, and emails, while avoiding cases like $80/hr or km/h that shouldn't be altered.  Brilliant
