### ISSUE TITLE
[Bug] Pause doesn't work on Firefox

### ISSUE THREAD

**Issue by gotmax23** [ken107/read-aloud#205]
Neither the "pause" button in the extension dialogue nor the keyboard shortcut pauses the reading on Firefox.

**Comment by ken107** [comment]
Thank you for reporting.  This happens if you have "Auto select" the voice, or choose one of the built-in voices provided by Firefox that show up at the top of the list.  These voices do not support pausing.  We could simulate pause by stopping and restarting from the start of the paragraph, but we don't have a reliable way to identify these voices that need this specific intervention.

**Comment by gotmax23** [comment]
Got it. Thanks for the quick response. Is there a voice that does support pausing available on Firefox? I didn't have this issue on chrome.

**Comment by ken107** [comment]
Yes, unfortunately on Firefox choices are limited.  Please choose "GoogleTranslate English", or one of the premium voices (you'll need to sign in, but you get 1 million free characters per month that should be enough for casual usage).  You could also try the "GoogleStandard" voices.

**Comment by gotmax23** [comment]
Thank you for this advice. I switched the voice to "GoogleTranslate English" and it seems to be the same as the default on chrome. Do you think it makes sense to document that pause doesn't work (with the default voice) on Firefox?

Either way, thanks for making this great browser extension!
