### ISSUE TITLE
Why no link to upload pdf and read it?

### ISSUE THREAD

**Issue by Serjeel-Ranjan-911** [ken107/read-aloud#209]
I know we can upload pdf and read it but this extension doesn't guide the user how? 
It will be decent if there is a link which will take user to upload page and use extension to read it as well.

**Comment by Serjeel-Ranjan-911** [comment]
please update for any feedback

**Comment by abmruman** [comment]
@Serjeel-Ranjan-911 I think if you open a PDF in your browser, and press read aloud or use the shortcut for the read action, it will upload the PDF and start reading. Or you can select the text in your PDF while it is open on your browser, you will see the option to `Read aloud selected text`.

**Comment by Serjeel-Ranjan-911** [comment]
Yes but to read from pdf it redirect us to the link and then only we can read it. This is the way I found it. So o thought maybe extension should tell me directly how to do it.

**Comment by ken107** [comment]
Thanks for the PR. However, because real estate on the main popup is rather precious, we can only include UI elements that will be used frequently.

PDF reading is only used occasionally by some users, im not sure it makes sense to include a link on the popup that appears to everyone.

User can drag the PDF into the browser to open it, then click Read Aloud, it will require a few extra steps, but the process is intuitive and straightforward.

**Comment by Serjeel-Ranjan-911** [comment]
> Thanks for the PR. However, because real estate on the main popup is rather precious, we can only include UI elements that will be used frequently.
> 
> PDF reading is only used occasionally by some users, im not sure it makes sense to include a link on the popup that appears to everyone.
> 
> User can drag the PDF into the browser to open it, then click Read Aloud, it will require a few extra steps, but the process is intuitive and straightforward.

ok. I will close the issue.
