### ISSUE TITLE
moron developer

### ISSUE THREAD

**Issue by aviwad** [ken107/read-aloud#233]
the developer promotes horse based medication (clearly denied by FDA on humans, denied by CDC for covid) on humans for covid. 

developer should be BANNED and kicked. message has been removed, what if they start spouting more nonsense, like anti-vaxxer content or something? we should switch to a better extension not made by actual clowns

**Comment by ken107** [comment]
These have been peer-reviewed and published:
https://journals.lww.com/americantherapeutics/Fulltext/2021/06000/Review_of_the_Emerging_Evidence_Demonstrating_the.4.aspx
https://covid19criticalcare.com/wp-content/uploads/2021/06/Ivermectin_for_Prevention_and_Treatment_of.98040.pdf

**Comment by ernstki** [comment]
An [independent meta-analysis](https://doi.org/10.1093/ofid/ofab358) based on [a large chunk of the same data](https://www.theguardian.com/science/2021/jul/16/huge-study-supporting-ivermectin-as-covid-treatment-withdrawn-over-ethical-concerns) as the two papers above was [retracted by its authors](https://academic.oup.com/ofid/article/8/8/ofab394/6346765) in July after they "learned that one of the studies on which this analysis was based has been withdrawn due to fraudulent data." Its authors were under pressure to do the responsible thing and retract because they published in a [highly-ranked](https://www.resurchify.com/impact/details/21100468501) journal under the auspices of Oxford University, instead of one published by a tiny [Ltd](https://www.investopedia.com/terms/l/ltd-limited.asp). run out of the back of a [tax and accounting consultancy](https://www.bloomberg.com/profile/company/1123087Z:LN). 

This is not to say that the people studying ivermectin as a therapeutic couldn't be on to something. But the sources you cite are not making a strong case for that; rather they are making a strong case for some [dubious](https://en.wikipedia.org/wiki/Pierre_Kory) [characters](https://en.wikipedia.org/wiki/Paul_E._Marik) out there being willing to [take people's money](https://web.archive.org/web/20210829010327/https://www.gofundme.com/f/help-us-get-lifesaving-drug-approved-for-covid19) for "academic support" of their maverick theories and sloppy science. People in the US and UK _already_ pay taxes to fund this kind of research, under the guidance of trusted, publicly-accountable institutions like the NIH and NHS.

To add some balance to your information diet, here is the US Food and Drug Administration's official statement on the matter, as well as an even-handed report from the Centers for Disease Control and Prevention which attempts to explain why people are so enamored with ivermectin and other non-evidenced based treatments right now:
* https://www.fda.gov/consumers/consumer-updates/why-you-should-not-use-ivermectin-treat-or-prevent-covid-19
* https://www.cdc.gov/vaccines/covid-19/downloads/SoVC-report14.pdf

**Comment by ken107** [comment]
The "dubious characters" you mentioned are front-line doctors and published researchers who stand to gain nothing by going against the medical consensus, instead risking their reputation and career.

And by what do you mean dubious?  [Dr. Paul Marik](https://researchers.evms.edu/display/person-paul-marik) has published hundreds of articles and been cited close to 40,000 times.  Calling someone with such credentials dubious really calls into question your motive.  Instead of raising money from crowd funding, would you rather they take funding from the pharmaceutical companies?  Which one is more likely a conflict of interest?

"Maverick theories and sloppy science": I'm afraid you don't have the qualifications to dismiss their work.  One of the studies in Egypt was indeed retracted, but this is the point of the meta-analysis.  It analyzes many studies, and so its conclusion is resilient against the withdrawal of any one study.  They have updated their meta-analysis to exclude the fraudulent study, and the conclusion remains largely the same.

Now the conclusion of the meta-analysis published in the Journal of Therapeutics is that the evidence for Ivermectin efficacy is only of "moderate certainty".  But it is nevertheless important.

What we're doing here is raising awareness that there is a body nof evidence behind Ivermectin.  People are being bombarded with the "horse dewormer" disinformation, perpetrated by orthodoxy zealots.  A medicine that's won the Nobel prize for its use in human, some 4 billion doses over several decades.  Calling it a horse dewormer is a lie.

**Comment by ken107** [comment]
And just to bolster the credentials of these "dubious characters".  Dr. Pier Kory testified to the US Senate on May 6 about the use of corticosteroids, e.g. dexamethasone, in early treatment of Covid-19 and was [censored](https://www.wsj.com/articles/youtube-cancels-the-u-s-senate-11612288061).  He was ridiculed, only to be validated weeks later by the Oxford recovery [trials](https://www.recoverytrial.net/news/low-cost-dexamethasone-reduces-death-by-up-to-one-third-in-hospitalised-patients-with-severe-respiratory-complications-of-covid-19).  The use of corticosteroids then became standard of care in hospitals.  These guys pioneers a treatment that saved lives.

**Comment by ken107** [comment]
Alright, well, fair enough.
