### ISSUE TITLE
[BUG] GoogleStandard Voices Break After Using Them For A Certain Time

### ISSUE THREAD

**Issue by Killstrike25** [ken107/read-aloud#268]
When you are using the googlestandard voices after using them for a certain period of time READALOUD asks for permissions to keep using the voice when you click the link to give the requested permissions it sends you to Google Clouds page and you need to solve a Captcha once doing this Google says you can close the page but READALOUD never works again using googlestandard voice it keeps prompting you for permissions and sending you back to that page

Edit: After using ReadAloud longer I noticed that the Premium Amazon Voices stop playing mid-sentence after a period of time but they work again if you click the Read Aloud Icon

The suggested fix for using [US English Female TTS (by Google) does not work with ReadAloud anymore - https://blog.readaloud.app/2020/09/if-read-aloud-keeps-stopping.html

Not sure if it matters but I am using Brave Browser

![image](https://user-images.githubusercontent.com/61766376/166862619-a2a14601-dca7-43d3-ab3d-9aec2c9f8aa5.png)

![image](https://user-images.githubusercontent.com/61766376/166862675-1e8cdc22-42a0-4141-aa1a-ff72e19a8b30.png)

![image](https://user-images.githubusercontent.com/61766376/166862705-993fa4db-9da4-4273-9405-41dd92fe6f37.png)

**Comment by ken107** [comment]
Sorry, the GoogleStandard voices are unreliable because we're only using its demo version, and Google decides arbitrarily when it wants to throttle a user and forces him/her to do the permission thing again.  Sometimes Google stops allowing that user to use the service altogether, and the permission basically stops working.

The "US English Female TTS" extension has been obsoleted.  Unfortunately there's no substitute for it at the moment.
