### ISSUE TITLE
pronounciations

### ISSUE THREAD

**Issue by rippledmindd** [ken107/read-aloud#282]
HI from Australia,
grating to listen to read aloud say 'wrong' pronounciations due to geography...

eg US say "Buddha" as BOODA (as in BOO)
in Australia we say BOODA (as in GOOD) - can there be a list of pronounciations to draw from eg suach as in ipad/iphone for speech to text

**Comment by ken107** [comment]
Please go to Options and pick the voice with the dialect you prefer.  If you pick an Australian English voice, it will speak with an Australian accent, and will pronounce the word accordingly.  If you pick the US English voice, it will speak the American accent.  

If you let Read Aloud auto-select a voice, given some English text, it will pick a US English voice by default, because it doesn't know what dialect you prefer.

**Comment by rippledmindd** [comment]
Thankyou - I had the microsoft english australian voice but didnt change - so I added the google english australian voices and yes they work.
Great work - I use this extension daily. Not becuase of visual impairment, just lazy... its like making my own podcasts
