### ISSUE TITLE
Needs a pause on list items

### ISSUE THREAD

**Issue by LiamDawe** [ken107/read-aloud#287]
Hello, a reader of my website notified me that for items in a list, if each item doesn't have a period at the end it ends up being read as one long thing.

Would it be possible for you to adjust whatever parser you use, to understand that anything in a bulleted or numbered list are individual items that needs a pause after / before each line? This would make the experience a lot nicer for many people I would think.

**Comment by ken107** [comment]
Could you provide the domain of the website where you encountered this issue?

I checked and we're already adding missing periods in HTML documents.  So you're probably seeing it on some website for which we have implemented custom handlers.

**Comment by ken107** [comment]
I see we have added periods at the end of each list item.  Is this what you also see?
![Screen Shot 2022-09-06 at 6 11 19 AM](https://user-images.githubusercontent.com/1976032/188519657-541505ea-998a-4ec5-a3ca-4e1521d2f94f.png)

If you don't hear pause after the period, it's probably because of the voice you have selected.  Unfortunately we don't control how the voice engines handle these situations.  Please try picking different voices to find one that works better.
