### ISSUE TITLE
Read bilingual text aloud

### ISSUE THREAD

**Issue by trionline1234** [ken107/read-aloud#324]
it will be useful for foreign language leaner when this extension can read aloud 2 language at once , because there is an extension to translate website to bilingual website.( https://chrome.google.com/webstore/detail/immersive-translate/bpoadfkcbjbfhfodiogcnhhhpibjhbnh)

**Comment by ken107** [comment]
I kept this issue open because it's a desirable feature.  But ultimately there's no algorithm to accurately break up a block of text into sections according to language, due to the nature of language detection being a heuristic process whose confidence level varies with the amount of text. Perhaps only an advanced AI model can do it.

But the proper solution to this problem is multilingual voices, i.e. a voice that can fluently read multiple languages.  There are few mutlilingual voice options currently, but in the future they should become more ubiquitous.
