### ISSUE TITLE
All voices sound very very robotic

### ISSUE THREAD

**Issue by 00-Python** [ken107/read-aloud#336]
The firefox extension randomly starts sounding terrible and stays that way no matter the voice i change it to.
Im running kali linux but it also happens in my Windows 10 VM. 
It is basically unusable.

**Comment by ken107** [comment]
Could you include some screenshots of what voices are available in the Options page?  The quality of the voices depend on the OS, and there's not much Read Aloud can do about that.  If you pick the cloud-based voices, those should work more consistently because they're synthesized from the cloud, such as the "ReadAloud Generic Voice".

**Comment by 00-Python** [comment]
Thanks yea, normally it must select that one by default and for some reason it changed. There are so many voices and all the ones i tried, about 20+, sounded terrible but that one works as it did before. Thanks :)
