### ISSUE TITLE
"Read aloud selected text" right click context menu no longer visible in Firefox ESR/Tor Browser after disabling/reinstalling

### ISSUE THREAD

**Issue by Shoozza** [ken107/read-aloud#370]
In the past there was a context menu entry "Read aloud selected text" in Firefox.

New installations of the Addon will not add this context menu entry.
If the Addon is disabled and enabled again (and the context menu was previously visible) the context menu will disappear.

Tested with Firefox ESR and Tor Browser.

**Comment by Shoozza** [comment]
Workaround:
1) Enable/Install Read Aloud addon from Firefox Addons Page
2) Download "read_aloud-1.66.0.xpi" file (visit addon page with a different browser)
3) Drag and drop xpi file into firefox tabbar
4) Switch to tab and click ok

Result:
Contextmenu appears again

Not sure why it's not appearing first time the addon is installed.

**Comment by ken107** [comment]
Turns out been doing it wrong all this time lol. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create

> persistent background pages:
in Chrome, menu items from persistent background pages are persisted. Create your menus in a [runtime.onInstalled](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onInstalled) listener.
in Firefox, menu items from persistent background pages are never persisted. Call menus.create unconditionally from the top level to register the menu items.

Thank you for reporting the issue.
