### ISSUE TITLE
'Read Aloud TTS' addon not found with Firefox on my apple silicon mac

### ISSUE THREAD

**Issue by sangshuduo** [ken107/read-aloud#378]
It happens when I click the addon icon on the toolbar as I wish it speech my Google Doc text.
The Firefox version is 123.0 (64-bit).

Anything I missed? Thanks.

**Comment by ken107** [comment]
To read aloud Google Docs on Firefox, you'll need to click on the "Extensions" menu in Google Docs and install the "Read Aloud TTS" addon from the **Google Workspace Marketplace**.  Then you can use that addon, which opens a sidebar, to read aloud Google Docs.  This browser extension on Firefox cannot read Google Docs directly due to technical limitations.

**Comment by sangshuduo** [comment]
> To read aloud Google Docs on Firefox, you'll need to click on the "Extensions" menu in Google Docs and install the "Read Aloud TTS" addon from the [Google Workspace Marketplace](https://workspace.google.com/marketplace/search/Read%20Aloud%20TTS). Then you can use that addon, which opens a sidebar, to read aloud Google Docs. This browser extension on Firefox cannot read Google Docs directly due to technical limitations.

Thanks.
