### ISSUE TITLE
Support ElevenLabs Custom Voices

### ISSUE THREAD

**Issue by semihsezer** [ken107/read-aloud#379]
[ElevenLabs](https://elevenlabs.io/) is a great new TTS library that creates very high quality TTS voices. Supporting this in the custom voices would be great! They have an intuitive and simple API.

**Comment by ken107** [comment]
The cost is too expensive, at approximately $1 per 5000 characters.  In other words, it costs 1 dollar to listen to a short news article.

The reason is that these voices are intended for commercial purposes, where the audio is synthesized once and then used again and again in marketing material, ads, voice overs, etc.  They are not intended for listening to articles and documents and books.
