### ISSUE TITLE
Constant Server 500 error

### ISSUE THREAD

**Issue by infineonnetworks** [ken107/read-aloud#436]
Utilizing the extension with Piper Joe voice and has been working great for a while, however as of noon today we have been getting a bunch of Server 500 errors in interruptions.
Network from our side has been stable.

**Comment by ken107** [comment]
Thank you for reporting the issue.  The server has been going up and down.  Turns out the Piper phonemizer process leaks memory and since we run it as a service, it's been consuming more and more memory.  When I restarted the process just now, it was taking up nearly all 16GB of memory.

Will update the service to restart the process daily.
