### ISSUE TITLE
Delay Between sentances

### ISSUE THREAD

**Issue by serverok** [ken107/read-aloud#45]
Is there anyway to reduce delay between sentences ?

**Comment by serverok** [comment]
The problem was with voice. Changing to google voice fixed it.

**Comment by ken107** [comment]
Could you tell me which voice you had selected where the problem occurred?  Did you have it "Auto Select"?

**Comment by serverok** [comment]
Initially it get auto selected. I am not sure which voice it was. I thought it is using google voice i used to use as it sounded similar, but there is more "sleep" time between sentences. Now with "US English Female Text-to-speech (by Google)", it is working perfectly fine.

I was using Chrome Speak before,  when i select a new text and speak, it used to stop current task, read new text.  Read Aloud just stop current task. Don't read the new selected text. An option for this will be great.

**Comment by ken107** [comment]
OK, the latter issue you describe is indeed a bug and I just provided a fix for it.  Thank you.

**Comment by ruffsl** [comment]
> when i select a new text and speak, it used to stop current task, read new text

Was there a ticket for this feature/option? I often just double click a paragraph the use the start reading shortcut key to listen to the paragraph (like in a busy forum comment thread), then will often skip ahead to select a new paragraph wishing to skip the rest of the previous selection.

The only way this seems to be possible as of writing is by using the option from the right-click drop down menu on the new selected text, rather than repeating the shortcut key used to start the reading initially. I'd like gain an option to enable a new shortcut key to cancel the previous selection and start from what ever is most currently selected.
