### ISSUE TITLE
Google Wavenet

### ISSUE THREAD

**Issue by nesrad** [ken107/read-aloud#58]
Any plans to use the new voices from Google Wavenet?
https://cloud.google.com/text-to-speech/

**Comment by nesrad** [comment]
I suspect Google will eventually make it free for non commercial use.

**Comment by t-k-** [comment]
@nesrad Hi, you can check out my extension here: https://github.com/t-k-/voice-instead-pro
I recently added Google Wavenet, feel free to try it out and welcome your feedback. Voice

Although Voice Instead is not free on Google Chrome Store, but once you have cloned the repository, you can just change [two lines of the code](https://github.com/t-k-/voice-instead-pro/blob/50b5112ac4929351c1cdd75fb6538a1ad4c39d19/src/background.js#L17-L18) to switch to "debug mode". And you get the full version for free! It is the bonus for being a developer :P  

My source code may look very ugly and unorganized, it is because I am not professional Javascript programmer and it is mainly to solve my needs, but I hope other developers can enjoy it as well.

**Comment by kkot** [comment]
Some extension like [Speechy](https://chrome.google.com/webstore/detail/speechy/flpjdaabfegkkifhogoilelmjcipihnp) allow to provide key to Google API Key.
@ken107 would you consider adding this option or merging Pull Request with this change.
I'm not sure how many people would use it. Probably only developers.

**Comment by ken107** [comment]
Yes, I'm thinking about doing that.  Thanks

**Comment by ken107** [comment]
Version 1.4.6 now supports Custom Voices
In Options, under Voice, select "Enable Custom Voices" and enter your GCP API key.

**Comment by kkot** [comment]
@ken107 thanks works great. Small remark, for me it was little confusing that first I need to select "Enable Custom Voices" and then select actual Wavenet voice.

**Comment by ken107** [comment]
Yes, I made it a bit obscure because, most people won't be using the feature.  But anyone savvy enough to have an AWS or GCP account should figure it out.
