### ISSUE TITLE
Suggest an export audio file feature

### ISSUE THREAD

**Issue by phatchuongit** [ken107/read-aloud#7]
I suggest a feature that allow user export the audio file. So the user can prepare and bring list of book in smartphone everywhere.

Thanks.

**Comment by orschiro** [comment]
This is a cool idea!

I imagine the following workflow: 

1. Visit website
2. Click the button of the extension
3. It converts the page to audio and allows you to download it to your local hard drive. 

This would be truly amazing!

**Comment by phatchuongit** [comment]
Hi @orschiro ,

Thank you for your workflow.

I beleived that @ken107 is working on this. That will be great if we can discuss more detail and the user expectation. If you can share with us @ken107 , @orschiro and I will help.

Thank,

**Comment by orschiro** [comment]
Indeed! Happy to give feedback and test any preview version available. :-)

**Comment by ken107** [comment]
Actually, as of the moment, converting an entire book to audio may cost as much as $5 using Amazon Polly voices, which are better for reading stories, and are billed at $4 per million characters.  That means I'll have to introduce some payment model.  As far as I know, the Chrome native text-to-speech function doesn't expose the raw audio stream or file.

Secondly, while the result is of perhaps acceptable quality for the price, there may be copyright issues to distribute such audios.

If we were to implement, the extension will call the server to perform the audio conversion.  The server will need to break the text up into pages or smaller, convert individual page into audio, then use FFMPEG to concatenate them to make the final audio.  There should be an edit function, so that the user can fix any errors in the text.

Will need to think more about this.  I actually have this pipeline already set up when I created https://ttstool.com.  But that site is intended for other purposes like creating voice narration tracks for YouTube videos.

**Comment by orschiro** [comment]
> Will need to think more about this. I actually have this pipeline already set up when I created https://ttstool.com. But that site is intended for other purposes like creating voice narration tracks for YouTube videos.

So, for now a workaround is to copy and paste the text from a website into your website to download it, right?

**Comment by ken107** [comment]
Yes, but I think there's a size limit, if you put too much text it might error out.

**Comment by ken107** [comment]
merge into #159
