### ISSUE TITLE
Version 1.12.0 broke AWS polly custom voices

### ISSUE THREAD

**Issue by mathiscode** [ken107/read-aloud#97]
After updating to version 1.12.0, AWS custom voices were disabled.

When attempting to re-enter the AWS id/secret, the following console error appears:

`ReferenceError: AWS is not defined`

**Comment by ken107** [comment]
Hi, unfortunately I had to remove aws-sdk.js temporarily because Mozilla required all 3rd-party libraries to have a link to an official released version.  And the version included in the extension is compiled from source, so it was violating the policy.  I need to put it back in carefully so as to satisfy the review process.

**Comment by mathiscode** [comment]
Oh, that makes sense! Thanks for such a useful extension!
